- name: Clone docker build repo
  git:
    repo: https://github.com/precurse/docker-stuff
    dest: "{{ docker_repo_path }}"
    update: yes
    force: yes

- name: Remove system docker-py
  apt:
    name: python-docker
    state: absent
  become: yes

- name: Install python-pip
  apt:
    name: python-pip
    state: present
    cache_valid_time: 3600
  become: yes

- name: Install docker-py
  pip:
    name: docker-py
    state: present
  become: yes

- name: Create volume(s)
  docker_volume:
    name: syncthing_config
  become: yes

# - name: Download alpine rootfs
#   command: ./fetch.sh
#   args:
#     chdir: "{{ docker_repo_path }}/alpine-armhf"
#     creates: "{{ docker_repo_path }}/alpine-armhf/rootfs.tar.gz"

- name: Build docker images
  docker_image:
    path: "{{ docker_repo_path }}/{{ item }}"
    name: "precurse/{{ item }}"
    buildargs:
      ARCH: arm

  become: yes
  with_items:
    # - alpine-armhf
    - networkupstools
    - smartospxe
    - syncthing
    - tftpd

- name: Create tftpd container
  docker_container:
    name: tftpd
    image: precurse/tftpd
    state: started
    restart_policy: unless-stopped
    published_ports:
      - "69:69/udp"
  become: yes

- name: Create smartospxe container
  docker_container:
    name: smartospxe
    image: precurse/smartospxe
    state: started
    restart_policy: unless-stopped
    published_ports:
      - "80:80/tcp"
  become: yes

- name: Create networkupstools container
  docker_container:
    name: networkupstools
    image: precurse/networkupstools
    state: started
    restart_policy: unless-stopped
    published_ports:
      - "3493:3493/tcp"
    devices:
      - /dev/bus/usb/001/005
  become: yes

- name: Create syncthing container
  docker_container:
    name: syncthing
    image: precurse/syncthing
    state: started
    restart_policy: unless-stopped
    network_mode: host
    volumes:
      - syncthing_config:/var/syncthing
      - /home/piranha/syncthing:/data
  become: yes
