- name: Install dependencies
  pkgin:
    name: "{{ item }}"
    state: present
  with_items:
    - build-essential
    - unzip
    - py27-pip
  become: yes

- name: Create syncthing group
  group:
    name: syncthing
    gid: 1001
    state: present
  become: yes

- name: Install Openstack Swift
  pip:
    name: "{{ item }}"
  with_items:
    - python-keystoneclient
    - python-swiftclient
  become: yes

- name: Check if rclone already exists
  stat:
    path: /home/piranha/rclone/rclone
  register: rclone_stat

- name: Download rclone
  get_url:
    url: "{{ rclone_url }}"
    dest: /home/piranha/rclone.zip
  become_user: piranha
  become: yes
  when: not rclone_stat.stat.exists

- name: Extract rclone
  unarchive:
    src: /home/piranha/rclone.zip
    dest: /home/piranha/
    remote_src: yes
  become_user: piranha
  become: yes
  when: not rclone_stat.stat.exists

- name: Move rclone
  shell: mv /home/piranha/rclone-*-amd64 /home/piranha/rclone
  become_user: piranha
  become: yes
  when: not rclone_stat.stat.exists

- name: Ensure rclone config directory exists
  file:
    path: /home/piranha/.config/rclone
    state: directory
  become_user: piranha
  become: yes

- name: Copy openrc
  template:
    src: openrc.j2
    dest: /home/piranha/openrc
  become_user: piranha
  become: yes

- name: Copy rclone.conf
  template:
    src: rclone.conf.j2
    dest: /home/piranha/.config/rclone/rclone.conf
  become_user: piranha
  become: yes

- name: Setup crontabs
  cron:
    name: "{{ item.name }}"
    user: piranha
    hour: "{{ (item.job | hash | list | map('int',0,16) | sum ) % 24 }}"
    minute: "{{ (item.job | hash | list | map('int',0,16) | sum ) % 60  }}"
    job: "{{ item.job }}"
  with_items: "{{ samba_cron }}"
  tags: cron
